### PR TITLE
fix: wrong operation of undo, redo in `customoBlockView`

### PR DESCRIPTION
**Pull request by js87zz**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description
* fixed wrong operation of undo, redo in `customoBlockView`
* added editor option test case

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Review by jung-han — APPROVED** [review]
완료입니다!

**Review by jungeun-cho — APPROVED** [review]
이견없습니다.

**Review by jajugoguma — APPROVED** [review]
이견 없습니다!

**Review by lja1018 — COMMENTED** [review]
리뷰완료합니다.

**Pull request merged**
