### PR TITLE
feat: add Italian translation

### PR DESCRIPTION
**Pull request by mredaelli**
### Please check if the PR fulfills these requirements
- [X] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [X] It does not introduce a breaking change or has a description of the breaking change

### Description
Translations for Italian

### CODE REVIEW

**Comment by sohee-lee7** [comment]
@mredaelli Thanks for the contribution

Could you fix your PR refer to https://github.com/nhnent/tui.editor/pull/205/files ?
Then I can merge it.

**Comment by mredaelli** [comment]
Should be done. Let me know if I missed something :)

**Comment by michgerts** [comment]
Looking forward for this merge. Thanks @mredaelli :)

**Comment by sohee-lee7** [comment]
Thank you @mredaelli !! I will merge it soon @michgerts :)

**Pull request merged**
