### PR TITLE
Use destroy instead of remove for vuejs

### PR DESCRIPTION
**Pull request by thomas-netlor**
### Please check if the PR fulfills these requirements
- [ ] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by caio-tenorio** [comment]
Thanks for that, i'm currently having a issue because of this.

**Review by js87zz — APPROVED** [review]
@thomas-netlor 
I will release the bugfix within next week. Thank you!

**Comment by bobvandevijver** [comment]
@js87zz Can I bother you to create a release? Looks like this bug is the only one blocking us to upgrade to v3 :)

**Comment by js87zz** [comment]
@thomas-netlor @caio-tenorio @bobvandevijver 
The vue-wrapper has been published(`v3.0.1`). The Main editor bug will probably be fixed and released within this week.
Thanks!

**Pull request merged**
