### PR TITLE
fix: overflow-X to lowercase

### PR DESCRIPTION
**Pull request by xjh22222228**
### Please check if the PR fulfills these requirements
- [ ] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Review by 000panther — APPROVED** [review]
I would really prefer this fix to be merged, my css preprocessor complains all the time and it should not cause any problems (more fix some)

**Review by extempl — APPROVED** [review]

**Comment by coeing** [comment]
Please merge this, the warning distracts from more important warnings :)

**Comment by coeing** [comment]
This merge should be a no-brainer as it should not destroy anything, but just removes the warning that distracts from other, more important warnings :)

**Comment by extempl** [comment]
Is tui editor abandoned?

**Pull request closed without merging**
