### PR TITLE
chore: make shell scripts in CI config safe

### PR DESCRIPTION
**Pull request by szepeviktor**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### CODE REVIEW

**Comment by szepeviktor** [comment]
No CI for PR-s??

**Comment by seonim-ryu** [comment]
@szepeviktor First of all, there is currently no CI set in pr. But for what reason did you modify the configuration file?

**Comment by szepeviktor** [comment]
There are 2 temporary variables used only ones.
And backticks are dangerous. Please see `shellcheck` for sustainable shell scripts.

**Comment by seonim-ryu** [comment]
@szepeviktor I understand what the problem is. I think this PR must be merged before I can test it. I'll tell you the result after merging. Thanks for contributing!

**Comment by szepeviktor** [comment]
All right.

Thank you for merging.

**Pull request merged**
