### PR TITLE
feat: markdown smart task plugin

### PR DESCRIPTION
**Pull request by js87zz**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description
* added smart task functionality

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Review by seonim-ryu — APPROVED** [review]
[1/27] 이견 없습니다! 근데 태스크 리스트에 `shift + ctrl + x` 숏컷 기능은 따로 작업하시는거죠~?

**Comment by js87zz** [comment]
@seonim-ryu 
아..키맵이 있어군요. 깜빡했네요;; 키맵도 추가해둘게요!

**Review by lja1018 — APPROVED** [review]
리뷰완료
고생하셨습니다!

**Review by shiren — APPROVED** [review]
LGTM

**Pull request merged**
