### PR TITLE
style: change from uppercase to lowercase (fix #2932)

### LINKED ISSUE #2932: fix: eslint num run build -> unsupported-css-property
## Describe the bug

apps/editor/src/css/contents.css 경로의 CSS 스타일 문제
```css
.ProseMirror {
  font-family: 'Open Sans', 'Helvetica Neue', 'Helvetica', 'Arial', '나눔바른고딕',
    'Nanum Barun Gothic', '맑은고딕', 'Malgun Gothic', sans-serif;
  color: #222;
  font-size: 13px;
  overflow-y: auto;
  overflow-X: hidden; <-- Here 
  height: calc(100% - 36px);
}
```

▲ [WARNING] "overflow-X" is not a known CSS property [unsupported-css-property]

## To Reproduce

`npm run build.... ` ?...

## Screenshots
스크린샷 2023-01-29 오후 5 16 07

## Desktop (please complete the following information):
 - none

## Smartphone (please complete the following information):
 - none

### PR DESCRIPTION
**Pull request by aihoshistar**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

react + tui.editor 를 사용한 프로젝트 코드 리뷰를 하고 있는데, npm run build 를 하니 이런 메세지가 출력 됬습니다. 

image

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by aihoshistar** [comment]
Screenshot 2023-03-12 at 3 11 31 AM


ㅠㅠ

**Review by emravoan — APPROVED** [review]
LGTM!

**Review by emravoan — APPROVED** [review]

**Review by IZGlassy — APPROVED** [review]

**Review by RefinedStone — APPROVED** [review]

**Review by IZGlassy — APPROVED** [review]

**Comment by aihoshistar** [comment]
@emravoan 

How can a pull request be merged?
I am very curious.

**Comment by emravoan** [comment]
> @emravoan
> 
> How can a pull request be merged? I am very curious.

@Kyungseo-Park I think a pull request be able to merge after getting approval from a maintainer.

**Pull request closed without merging**
