### PR TITLE
fix: `getHTML` API

### PR DESCRIPTION
**Pull request by js87zz**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description
* fixed `getHTML` API result
```js
// as-is
console.log(editor.getHTML()); // <h1 data-nodeid="1">heading</h1>

// to-be
console.log(editor.getHTML()); // <h1>heading</h1>
```

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Review by jung-han — APPROVED** [review]
완료입니다~ 고생하셨어요~

**Review by jungeun-cho — APPROVED** [review]
리뷰완료합니다.
editorCore, view에서 `setCodeBlockLanguages`가 삭제되었는데 더이상 필요없어진거죠?~

**Review by lja1018 — APPROVED** [review]
리뷰완료합니다.

**Comment by js87zz** [comment]
> 리뷰완료합니다.
> editorCore, view에서 `setCodeBlockLanguages`가 삭제되었는데 더이상 필요없어진거죠?~

@jungeun-cho 
넵~ `setCodeBlockLanguages`은 더이상 사용하지 않습니다!

**Pull request merged**
